// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.



package frc.robot.commands;
import java.rmi.registry.LocateRegistry;
import java.util.ArrayList;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;

import com.fasterxml.jackson.databind.ObjectMapper;

import org.opencv.ml.Ml;

import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriverAssist extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final Drivetrain m_drivetrain;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private boolean isRedTeam;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public DriverAssist(Drivetrain subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_drivetrain = subsystem;
        addRequirements(m_drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        if (DriverStation.getAlliance() == DriverStation.Alliance.Red) {
            isRedTeam = true;
        } else if (DriverStation.getAlliance() == DriverStation.Alliance.Blue) {
            isRedTeam = false;
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        
        //for object in detections, find the lowest distance that is the correct color, drive at it 
        //read JSON
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        NetworkTable table = inst.getTable("ML");
        NetworkTableEntry distance_red_entry = table.getEntry("distance_red");
        NetworkTableEntry angle_red_entry = table.getEntry("angle_red");
        NetworkTableEntry distance_blue_entry = table.getEntry("distance_blue");
        NetworkTableEntry angle_blue_entry = table.getEntry("angle_blue");
        double distance_red = distance_red_entry.getDouble(0.0);
        double angle_red = angle_red_entry.getDouble(0.0);
        double distance_blue = distance_blue_entry.getDouble(0.0);
        double angle_blue = angle_blue_entry.getDouble(0.0);

        if(isRedTeam){
            chase(distance_red, angle_red);
        }
        else if(!isRedTeam){
            chase(distance_blue, angle_blue);
        }
        //https://github.com/The-Charge/SulfuricAcid2021/blob/master/src/main/java/frc/robot/commands/RunTurretVision.java
    }
    private void chase(double distance, double angle){
        if(distance == -1) return;
        double rightSpeed = -RobotContainer.getInstance().getrightJoystick().getY();
        double leftSpeed = -RobotContainer.getInstance().getleftJoystick().getY();
        double speed = (leftSpeed + rightSpeed)/2;
        if(Math.abs(angle) < 1) m_drivetrain.run(speed, speed);
        else {
            m_drivetrain.run(speed + (speed*angle/30), speed - (speed*angle/30));
        }
        
    }
    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        NetworkTable table = inst.getTable("ML");
        NetworkTableEntry area_red_entry = table.getEntry("area_red");
        NetworkTableEntry area_blue_entry = table.getEntry("area_blue");
        double area_red = area_red_entry.getDouble(0.0);
        double area_blue = area_blue_entry.getDouble(0.0);
        if(isRedTeam){
            return(area_red < 100);
        }
        else if(!isRedTeam){
            return(area_blue < 100);
        }
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }


  
}

