// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Drivetrain;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Pivot;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class PivotTillPitchStopped extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final Pivot m_pivot;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final boolean m_direction;
    private final Drivetrain m_gyroHost;
    private int consecutiveTimesPitchStopped =0;
    private double lastPitch; 
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public PivotTillPitchStopped(boolean forward, Pivot subsystem, Drivetrain gyroHost) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_pivot = subsystem;
        addRequirements(m_pivot);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_direction = forward;
        m_gyroHost = gyroHost;
        addRequirements(m_gyroHost);
    }

    // Called when the command is initially scheduled.
    
    @Override
    public void initialize() {
        consecutiveTimesPitchStopped = 0;
        lastPitch = m_gyroHost.getPitch();
        if (m_direction) m_pivot.increaseAngle(2);
        else m_pivot.increaseAngle(-2);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double newPitch = m_gyroHost.getPitch();
        if (Math.abs(newPitch-lastPitch) < 0.1) consecutiveTimesPitchStopped++;
        else {
            lastPitch = newPitch;
            if (m_direction) m_pivot.increaseAngle(2);
            else m_pivot.increaseAngle(-2);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return (consecutiveTimesPitchStopped > 5);
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
