package frc.robot.commands;


import edu.wpi.first.wpilibj2.command.InstantCommand;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;
import frc.robot.subsystems.Pivot;
import frc.robot.subsystems.Telescope;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class StopClimb extends InstantCommand {

    private Drivetrain m_drivetrain;
    private Telescope m_telescope;
    private Pivot m_pivot;

    public StopClimb(Drivetrain drivetrain, Telescope telescope, Pivot pivot) {
        m_drivetrain = drivetrain;
        m_telescope = telescope;
        m_pivot = pivot;
    }

    @Override
    public void initialize() {
        m_drivetrain.stop();
        m_pivot.stopPivot();
        m_telescope.stopTele(); 
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED

    }

    
}