package frc.robot.commands;


import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.subsystems.Climber;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class StopClimb extends InstantCommand {

    Drivetrain m_drivetrain;
    Climber m_climber;
    

    public StopClimb(Drivetrain drivetrain, Climber climber){
        m_drivetrain = drivetrain;
        m_climber = climber;
    }

    @Override
    public void initialize() {
        m_drivetrain.stop();
        m_climber.stopPivot();
        m_climber.stopTele();
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
